create table persistent_logins
(
    username  varchar(64) not null,
    series    varchar(64) not null
        primary key,
    token     varchar(64) not null,
    last_used timestamp   not null
);

alter table persistent_logins
    owner to postgres;

create table users
(
    is_verified boolean,
    social_id   integer,
    id          bigserial
        primary key,
    email       varchar(255),
    password    varchar(255),
    role        varchar(255),
    social_name varchar(255),
    username    varchar(255),
    uuid        varchar(255)
        unique,
    temp_email varchar(255)
);

alter table users
    owner to postgres;

create table verification_token
(
    is_expired  boolean      not null,
    expiry_date timestamp(6) not null,
    id          bigserial
        primary key,
    user_id     bigint       not null
        constraint fk3asw9wnv76uxu3kr1ekq4i1ld
            references users,
    token       varchar(255) not null,
    type        varchar(255) not null
        constraint verification_token_type_check
            check ((type)::text = ANY
                   (ARRAY [('EMAIL_VERIFICATION'::character varying)::text, ('PASSWORD_RESET'::character varying)::text]))
);

alter table verification_token
    owner to postgres;

create table drumkit
(
    id          bigint generated by default as identity
        primary key,
    title       varchar(255)     not null,
    cost        double precision not null,
    description text,
    image_url   varchar(255)
);

alter table drumkit
    owner to postgres;

